version: "2"
services:
  rabbit:
    image: rabbitmq:3.8.3-management
    ports:
      - "15672:15672"
    hostname: rabbitmq
    restart: on-failure

  redis:
    image: redis:5.0.5
    ports:
      - "6379:6379"
    expose:
      - "6379"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    restart: on-failure
    volumes:
      - redis-data:/data

  fastapi:
    build:
      context: microservices/fastapi
    links:
      - rabbit
    env_file:
      - ./microservices/fastapi/.env

  ml-service:
    build:
      context: microservices/ml-service
    links:
      - rabbit
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      RABBIT_PASSWORD: "guest"
      RABBIT_USER: "guest"
      RABBIT_HOST: "rabbit"
      RABBIT_PORT: "5672"

  # db-service:
  #   build:
  #     context: microservices/db-service
  #   depends_on:
  #     - rabbit
  #   environment:
  #     REDIS_HOST: "redis"
  #     REDIS_PORT: "6379"
  #     RABBIT_PASSWORD: "guest"
  #     RABBIT_USER: "guest"
  #     RABBIT_HOST: "rabbit"
  #     RABBIT_PORT: "5672"
  traefik:
    build:
      context: .
      dockerfile: ./microservices/traefik/Dockerfile
    depends_on:
      - fastapi
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "80:80"
      - "8080:8080"

volumes:
  redis-data: {}
  production_traefik: {}
